{ mkBunDerivation, ... }:

mkBunDerivation {
  pname = "sealgair.dev";
  version = "1.0.0";
  src = ./.;
  bunNix = ./bun.nix; # generated by bun2nix
  # For Astro, your entrypoint might be different, e.g. "astro.config.mjs" or "index.ts"
}

